package com.nutricatch.dev.helper

val labelResult = arrayOf(
    "apel",
    "ayam_goreng",
    "ayam_pop",
    "bakso_kuah",
    "cumi_tepung",
    "daging_rendang",
    "gado_gado",
    "gulai_ikan",
    "ikan_goreng",
    "kacang_rebus",
    "kentang_goreng",
    "lemon",
    "mangga",
    "mie_goreng",
    "mie_kuah",
    "nanas",
    "nasi_goreng",
    "opor_ayam",
    "pear",
    "pempek",
    "pisang",
    "sate_bakar",
    "sayur_asam",
    "sayur_bayam",
    "semangka",
    "somay",
    "tahu_goreng",
    "telur_balado",
    "telur_dadar",
    "tempe_goreng",
)

val foodLabelsMap = mapOf(
    "apel" to "Apel",
    "ayam_goreng" to "Ayam Goreng",
    "ayam_pop" to "Ayam Pop",
    "bakso_kuah" to "Bakso Kuah",
    "cumi_tepung" to "Cumi Tepung",
    "daging_rendang" to "Daging Rendang",
    "gado_gado" to "Gado Gado",
    "gulai_ikan" to "Gulai Ikan",
    "ikan_goreng" to "Ikan Goreng",
    "kacang_rebus" to "Kacang Rebus",
    "kentang_goreng" to "Kentang Goreng",
    "lemon" to "Lemon",
    "mangga" to "Mangga",
    "mie_goreng" to "Mie Goreng",
    "mie_kuah" to "Mie Kuah",
    "nanas" to "Nanas",
    "nasi_goreng" to "Nasi Goreng",
    "opor_ayam" to "Opor Ayam",
    "pear" to "Pear",
    "pempek" to "Pempek",
    "pisang" to "Pisang",
    "sate_bakar" to "Sate Bakar",
    "sayur_asam" to "Sayur Asam",
    "sayur_bayam" to "Sayur Bayam",
    "semangka" to "Semangka",
    "somay" to "Somay",
    "tahu_goreng" to "Tahu Goreng",
    "telur_balado" to "Telur Balado",
    "telur_dadar" to "Telur Dadar",
    "tempe_goreng" to "Tempe Goreng"
)